name: Release

on:
  workflow_dispatch: {}

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
      - uses: actions/checkout@v2
      - uses: anatawa12/something-releaser@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: generate version information
        run: |
          gh-export-variable VERSION "$(date '+%Y%m%d%H%M%S')"
          # find DOWNLOADER_VERSION in Dockerfile
          DOWNLOADER_VERSION="$(grep 'ARG DOWNLOADER_VERSION=' < image/Dockerfile \
                                | sed 's/.*=//' | head -1 | sed 's/^ *\| *$//')"
          # error if not found (empty string)
          if [ -z $DOWNLOADER_VERSION ]; then
              echo "DOWNLOADER_VERSION not found" >&2
              exit 1
          fi
          gh-export-variable DOWNLOADER_VERSION "$DOWNLOADER_VERSION"

      - name: download & generate downloader
        run: |
          curl -L "https://github.com/anatawa12/mod-downloader/releases/download/v${DOWNLOADER_VERSION}/mod-downloader-${DOWNLOADER_VERSION}.jar" \
              > mod-downloader-gen.jar
          java -jar mod-downloader-gen.jar --new-embed \
              --url "https://github.com/MilitaryGameOrganization/naval-review-server-server/releases/latest/download/mods.txt" \
              --name "JAM Server" \
              --dest ./mod-downloader.jar

      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: mod-downloader.jar
          retention-days: 30

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./image
          platforms: |-
            linux/amd64
            linux/arm64
          tags: |-
            ghcr.io/militarygameorganization/naval-review-server-server:${{ env.VERSION }}
            ghcr.io/militarygameorganization/naval-review-server-server:latest

      - name: tag & push release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git tag "$VERSION"
          git push origin "$VERSION"
          gh release create "$VERSION" --notes "release on $(git rev-parse HEAD)"
          gh release upload "$VERSION" "mod-downloader.jar"
          gh release upload "$VERSION" "image/mods.txt"
          gh release upload "$VERSION" "docker-compose.yml"
